[package]
name = "test-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
xhtml_parser = { path = "../../rust-crates/xhtml_parser" }

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
debug = false
