[package]
name = "test-xhtml_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
xhtml_parser = "0.2"

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
debug = false
